### ISSUE TITLE
SpringBoot I/O error on GET request for "http://localhost:8080/realms/spring/.well-known/openid-configuration": Connection refused

### ISSUE THREAD

**Issue by chengkuangan** [zvigrinberg/keycloak-examples#1]
@zvigrinberg I run the keycloak and springboot apps on local laptop. Both running in containers fine with keycloak at port `8080` and springboot at `8081`. I managed to request TOKEN from the keycloak server. Springboot is with default settings and when I tried to `GET` using `my-user`, I received the following in the SpringBoot log, may I know what could be wrong?

```
Caused by: java.lang.IllegalArgumentException: Unable to resolve the Configuration with the provided Issuer of "http://localhost:8080/realms/spring"
	at org.springframework.security.oauth2.jwt.JwtDecoderProviderConfigurationUtils.getConfiguration(JwtDecoderProviderConfigurationUtils.java:161) ~[spring-security-oauth2-jose-6.0.3.jar!/:6.0.3]
	at org.springframework.security.oauth2.jwt.JwtDecoderProviderConfigurationUtils.getConfigurationForIssuerLocation(JwtDecoderProviderConfigurationUtils.java:79) ~[spring-security-oauth2-jose-6.0.3.jar!/:6.0.3]
	at org.springframework.security.oauth2.jwt.JwtDecoders.fromIssuerLocation(JwtDecoders.java:93) ~[spring-security-oauth2-jose-6.0.3.jar!/:6.0.3]
	at org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerJwtConfiguration$JwtDecoderConfiguration.lambda$jwtDecoderByIssuerUri$3(OAuth2ResourceServerJwtConfiguration.java:143) ~[spring-boot-autoconfigure-3.0.6.jar!/:3.0.6]
	at org.springframework.security.oauth2.jwt.SupplierJwtDecoder.lambda$new$0(SupplierJwtDecoder.java:36) ~[spring-security-oauth2-jose-6.0.3.jar!/:6.0.3]
	... 86 common frames omitted
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8080/realms/spring/.well-known/openid-configuration": Connection refused
	at org.springframework.web.client.RestTemplate.createResourceAccessException(RestTemplate.java:888) ~[spring-web-6.0.8.jar!/:6.0.8]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:868) ~[spring-web-6.0.8.jar!/:6.0.8]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:714) ~[spring-web-6.0.8.jar!/:6.0.8]
	at org.springframework.security.oauth2.jwt.JwtDecoderProviderConfigurationUtils.getConfiguration(JwtDecoderProviderConfigurationUtils.java:150) ~[spring-security-oauth2-jose-6.0.3.jar!/:6.0.3]
	... 90 common frames omitted
Caused by: java.net.ConnectException: Connection refused
```

**Comment by chengkuangan** [comment]
Sorry, my mistake, the `localhost` is not resolvable within container. I changed to run this in `docker compose` mode, the name resolvable now. but I hit into another issue with the following error:

docker-compose.yaml:

```
version: '2'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    ports:
     - 8080:8080
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
  springboot:
    image: docker.io/chengkuan/keycloak-integration-springboot:0.0.1
    ports:
     - 8081:8081
    environment:
     - KEYCLOAK_SERVER_ADDRESS=http://keycloak:8080
```

Imported the keycloak config for springboot.

Get the TOKEN:
```
export USER=my-user
    export PASSWORD=password
    export CLIENT_ID=spring-boot-app
    export CLIENT_SECRET=ZjvIwT5SuQ3wrqwW1kst4vxhCtvgcKo7
    export KEYCLOAK_URL=localhost:8080
(base) ganck@chgan-mac springboot % export TOKEN=$(curl -X POST 'http://'${KEYCLOAK_URL}'/realms/spring/protocol/openid-connect/token' --user ''$CLIENT_ID':'$CLIENT_SECRET'' --header 'content-type: application/x-www-form-urlencoded' --data-urlencode 'username='${USER}''  --data-urlencode 'password='${PASSWORD}'' --data-urlencode 'grant_type=password' | jq .access_token | tr -d "\"") \
    && echo && echo $TOKEN
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2421  100  2367  100    54  34041    776 --:--:-- --:--:-- --:--:-- 35086

eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJodjZjM3JuYTlrbVlPYmFpWVlqdUlSU0hVSTJtR0ZMSGNRQjBIbFhnUl80In0.eyJleHAiOjE3MjcxNDg5NDYsImlhdCI6MTcyNzE0ODY0NiwianRpIjoiNzU1OWNkNDEtMWVhZC00MWQ5LWI2NTktMDljZDU3ZjhjODI5IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9zcHJpbmciLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiMTQ5NGY0NjItM2MxYi00NGJkLThjNmYtOGZmNjllZGU1ZjZjIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoic3ByaW5nLWJvb3QtYXBwIiwic2Vzc2lvbl9zdGF0ZSI6IjRjZGQ1MTE1LWRmYWUtNGY0NS04MjQ3LWVjM2IwNjhhZmE2OSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiLyoiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtc3ByaW5nIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InNwcmluZy1ib290LWFwcCI6eyJyb2xlcyI6WyJyZWd1bGFyLXVzZXIiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiY2FuX3dyaXRlX2VudGl0eSBlbWFpbCBwcm9maWxlIiwic2lkIjoiNGNkZDUxMTUtZGZhZS00ZjQ1LTgyNDctZWMzYjA2OGFmYTY5IiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJteS11c2VyIiwiZ2l2ZW5fbmFtZSI6IiIsImN1c3RvbVBlcnJtaXNzaW9ucyI6eyJjYW5DcmVhdGVJdGVtcyI6InRydWUifSwiZmFtaWx5X25hbWUiOiIifQ.fqXdChzY1-aQb6MzwHxvYZxfAq57J164x9XeUy3fFbJlLoJdYRI8XYLMS5wlveoWZjm507g1Jz5zw-KU7hURZvcytNRz1KVDoJVqS27LYM4EvHRwnZl4gjmsEC2GOHWKftw9sjbT815hPRHjD0P4rRGrQ1GBMiXkxTPRDIp3dhdCZN2phZJuAPY50mCnYedYJUhhCYWB_VPAXc62jLAxMgUfqQ6AGT-n43_Tt1oiKDPcujysvsW6k_h3_NUjNdDQY6VXmnzC5Bk_ckBkThOgFd41z_wvlweve_4-yWbLLF7etTNsJsQNvrAoAwUjL7lSA7lZQM6-C-4y7s7GOWFf5g
```

Request with the TOKEN:
```
curl -i -X GET http://$SERVICE_URL/items/demo-item --header 'Authorization: Bearer '$TOKEN''
HTTP/1.1 401 
WWW-Authenticate: Bearer error="invalid_token", error_description="An error occurred while attempting to decode the Jwt: The iss claim is not valid", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Length: 0
Date: Tue, 24 Sep 2024 03:31:02 GMT
```

**Comment by zvigrinberg** [comment]
Hi @chengkuangan 
Can you please set environment variable `LOG_LEVEL=debug` in docker-compose file,  and restart spring boot application container , and then try again  ?

Also make sure that the JWT Token is indeed populated  in the `Authorization` Header when invoking the `GET` request, by invoking this way:
```shell
 bash -x -c "curl -i -X GET http://$SERVICE_URL/items/demo-item --header 'Authorization: Bearer '$TOKEN''
 ```
And then send logs from spring boot application container
```shell
docker logs container_name
```
So i'll have more context and information to troubleshoot.
